GET http://localhost:8080/books

POST http://localhost:8080/books
Content-Type: application/json

{
    "title":"Java",
    "author":"James"
}

PUT http://localhost:8080/books/2
Content-Type: application/json

{
    "title":"Spring Boot",
    "author":"D"
}

DELETE http://localhost:8080/books/1